// Highlighted sidebar items
export const NEW = ['Marquee', 'Shimmer Button'];
export const UPDATED = [];

// Used for main sidebar navigation
export const CATEGORIES = [
  {
    name: 'ReactBits',
    subcategories: [
      'Squares',
      'Matrix Code',
      'ASCII Text',
      'Blur Text',
      'Circular Text',
      'Count Up',
      'Curved Loop',
      'Decrypted Text',
      'Falling Text',
      'Fuzzy Text',
      'Glitch Text',
      'Gradient Text',
      'Rotating Text',
      'Scrambled Text',
      'Scroll Float',
      'Scroll Reveal',
      'Scroll Velocity',
      'Shiny Text',
      'Shuffle',
      'Split Text',
      'Text Cursor',
      'Text Pressure',
      'Text Type',
      'True Focus',
      'Variable Proximity',
      'Animated Content',
      'Antigravity',
      'Blob Cursor',
      'Click Spark',
      'Crosshair',
      'Cubes',
      'Electric Border',
      'Fade Content',
      'Ghost Cursor',
      'ReactBits Glare Hover',
      'Gradual Blur',
      'Image Trail',
      'Laser Flow',
      'Logo Loop',
      'Magic Rings',
      'Magnet',
      'Magnet Lines',
      'Meta Balls',
      'Metallic Paint',
      'Noise',
      'Orbit Images',
      'Pixel Trail',
      'Pixel Transition',
      'Ribbons',
      'Shape Blur',
      'Splash Cursor',
      'Star Border',
      'Sticker Peel',
      'Strands',
      'Target Cursor',
      'Animated List',
      'Border Glow',
      'Bounce Cards',
      'Bubble Menu',
      'Card Nav',
      'Card Swap',
      'Carousel',
      'Chroma Grid',
      'Circular Gallery',
      'Counter',
      'Curved Input',
      'Decay Card',
      'ReactBits Dock',
      'Dome Gallery',
      'Elastic Slider',
      'Flowing Menu',
      'Fluid Glass',
      'Flying Posters',
      'Folder',
      'Glass Icons',
      'Glass Surface',
      'Gooey Nav',
      'Infinite Menu',
      'Lanyard',
      'Line Sidebar',
      'Magic Bento',
      'Masonry',
      'Model Viewer',
      'Pill Nav',
      'Pixel Card',
      'Profile Card',
      'Reflective Card',
      'Scroll Stack',
      'Spotlight Card',
      'Stack',
      'Staggered Menu',
      'Stepper',
      'Tilted Card',
      'Aurora',
      'Balatro',
      'Ballpit',
      'Beams',
      'Color Bends',
      'Dark Veil',
      'Dither',
      'Dot Field',
      'Dot Grid',
      'Evil Eye',
      'Faulty Terminal',
      'Ferrofluid',
      'Floating Lines',
      'Galaxy',
      'Gradient Blinds',
      'Grainient',
      'Grid Distortion',
      'Grid Motion',
      'Grid Scan',
      'Hyperspeed',
      'Iridescence',
      'Letter Glitch',
      'Lightfall',
      'Lightning',
      'Light Pillar',
      'ReactBits Light Rays',
      'Line Waves',
      'Liquid Chrome',
      'Liquid Ether',
      'Orb',
      'ReactBits Particles',
      'Pixel Blast',
      'Pixel Snow',
      'Plasma',
      'Plasma Wave',
      'Prism',
      'Prismatic Burst',
      'Radar',
      'Ripple Grid',
      'Shape Grid',
      'Side Rays',
      'Silk',
      'Soft Aurora',
      'Threads',
      'Waves',
    ],
  },
  {
    name: 'MagicUI',
    subcategories: [
      'Marquee',
      'Shimmer Button',
      'Meteors',
      'Border Beam',
      'Animated Gradient Text',
      'Dot Pattern',
      'Retro Grid',
      'Number Ticker',
      'Bento Grid',
      'Grid Pattern',
      'Android',
      'Animated Beam',
      'Animated Grid Pattern',
      'Animated Circular Progress Bar',
      'Animated Shiny Text',
      'Animated Subscribe Button',
      'Avatar Circles',
      'Aurora Text',
      'Backlight',
      'Client Tweet Card',
      'Code Comparison',
      'Blur Fade',
      'Comic Text',
      'Magic Animated List',
      'Confetti',
      'Dock',
      'Dotted Map',
      'Flickering Grid',
      'File Tree',
      'Glare Hover',
      'Globe',
      'Hexagon Pattern',
      'Hyper Text',
      'Highlighter',
      'Interactive Grid Pattern',
      'Interactive Hover Button',
      'iPhone',
      'Icon Cloud',
      'Lens',
      'Kinetic Text',
      'Line Shadow Text',
      'Light Rays',
      'Morphing Text',
      'Neon Gradient Card',
      'Noise Texture',
      'Orbiting Circles',
      'Pixel Image',
      'Pointer',
      'Progressive Blur',
      'Pulsating Button',
      'Rainbow Button',
      'Ripple',
      'Ripple Button',
      'Scroll Progress',
      'Shine Border',
      'Shiny Button',
      'Sparkles Text',
      'Spinning Text',
      'Striped Pattern',
      'Smooth Cursor',
      'Terminal',
      'Text 3D Flip',
      'Text Reveal',
      'Text Animate',
      'Tweet Card',
      'Typing Animation',
      'Video Text',
      'Warp Background',
      'Word Rotate',
      'Animated Theme Toggler',
      'Cool Mode',
      'Dia Text Reveal',
      'Glyph Matrix',
      'Hero Video Dialog',
      'Magic Card',
      'Particles',
      'Scroll Based Velocity',
      'Safari',
    ],
  },
  {
    name: '21st.dev',
    subcategories: [
      '21st Accordion',
      '21st Animated Background',
      '21st Animated Group',
      '21st Animated Number',
      '21st Border Trail',
      '21st Carousel',
      '21st Cursor',
      '21st Dialog',
      '21st Disclosure',
      '21st Dock',
      '21st Glow Effect',
      '21st Image Comparison',
      '21st In View',
      '21st Infinite Slider',
      '21st Magnetic',
      '21st Morphing Dialog',
      '21st Morphing Popover',
      '21st Progressive Blur',
      '21st Scroll Progress',
      '21st Sliding Number',
      '21st Spinning Text',
      '21st Spotlight',
      '21st Text Effect',
      '21st Text Loop',
      '21st Text Morph',
      '21st Text Roll',
      '21st Text Scramble',
      '21st Text Shimmer',
      '21st Text Shimmer Wave',
      '21st Tilt',
      '21st Toolbar Dynamic',
      '21st Toolbar Expandable',
      '21st Transition Panel',
      '21st Direction Aware Tabs',
      '21st Dynamic Island',
      '21st Expandable',
      '21st Family Button',
      '21st Animated Button',
      '21st Gradient Heading',
      '21st Logo Carousel',
      '21st Minimal Card',
      '21st Neumorph Button',
      '21st Loading Carousel',
      '21st Popover Form',
      '21st Shader Lens Blur',
      '21st Shift Card',
      '21st Side Panel',
      '21st Texture Card',
      '21st Texture Button',
      '21st 3D Carousel',
    ],
  },
];
