const motionComponents = [
  ['accordion', 'Accordion'],
  ['animated-background', 'Animated Background'],
  ['animated-group', 'Animated Group'],
  ['animated-number', 'Animated Number'],
  ['border-trail', 'Border Trail'],
  ['carousel', 'Carousel'],
  ['cursor', 'Cursor'],
  ['dialog', 'Dialog'],
  ['disclosure', 'Disclosure'],
  ['dock', 'Dock'],
  ['glow-effect', 'Glow Effect'],
  ['image-comparison', 'Image Comparison'],
  ['in-view', 'In View'],
  ['infinite-slider', 'Infinite Slider'],
  ['magnetic', 'Magnetic'],
  ['morphing-dialog', 'Morphing Dialog'],
  ['morphing-popover', 'Morphing Popover'],
  ['progressive-blur', 'Progressive Blur'],
  ['scroll-progress', 'Scroll Progress'],
  ['sliding-number', 'Sliding Number'],
  ['spinning-text', 'Spinning Text'],
  ['spotlight', 'Spotlight'],
  ['text-effect', 'Text Effect'],
  ['text-loop', 'Text Loop'],
  ['text-morph', 'Text Morph'],
  ['text-roll', 'Text Roll'],
  ['text-scramble', 'Text Scramble'],
  ['text-shimmer', 'Text Shimmer'],
  ['text-shimmer-wave', 'Text Shimmer Wave'],
  ['tilt', 'Tilt'],
  ['toolbar-dynamic', 'Toolbar Dynamic'],
  ['toolbar-expandable', 'Toolbar Expandable'],
  ['transition-panel', 'Transition Panel'],
].map(([slug, title]) => ({
  slug,
  title,
  author: 'motion-primitives',
  project: 'Motion Primitives',
  repo: 'ibelick/motion-primitives',
  path: `components/core/${slug}.tsx`,
  twentyFirstUrl: `https://21st.dev/@ibelick/components/${slug}`,
}));

const cultComponents = [
  ['direction-aware-tabs', 'Direction Aware Tabs'],
  ['dynamic-island', 'Dynamic Island'],
  ['expandable', 'Expandable'],
  ['family-button', 'Family Button'],
  ['bg-animate-button', 'Animated Button', 'bg-animated-button'],
  ['gradient-heading', 'Gradient Heading'],
  ['logo-carousel', 'Logo Carousel'],
  ['minimal-card', 'Minimal Card'],
  ['neumorph-button', 'Neumorph Button'],
  ['loading-carousel', 'Loading Carousel'],
  ['popover-form', 'Popover Form'],
  ['shader-lens-blur', 'Shader Lens Blur'],
  ['shift-card', 'Shift Card'],
  ['side-panel', 'Side Panel', 'side-panel-video'],
  ['texture-card', 'Texture Card'],
  ['texture-button', 'Texture Button'],
  ['three-d-carousel', '3D Carousel', '3d-carousel'],
].map(([slug, title, marketplaceSlug = slug]) => ({
  slug: `cult-${slug}`,
  upstreamSlug: slug,
  marketplaceSlug,
  title,
  author: 'cult-ui',
  project: 'Cult UI',
  repo: 'nolly-studio/cult-ui',
  path: `apps/www/registry/default/ui/${slug}.tsx`,
  twentyFirstUrl: `https://21st.dev/@cult-ui/components/${marketplaceSlug}`,
}));

const pascalCase = value => value
  .split('-')
  .map(part => part === '3d' ? '3D' : `${part[0].toUpperCase()}${part.slice(1)}`)
  .join('');

export const TWENTY_FIRST_COMPONENTS = [...motionComponents, ...cultComponents].map(component => ({
  ...component,
  name: `TwentyFirst${pascalCase(component.slug)}`,
  displayTitle: `21st ${component.title}`,
  routeSlug: `21st-${component.title.toLowerCase().replace(/\s+/g, '-')}`,
}));
